### ISSUE TITLE
Separate local folder for each host

### ISSUE THREAD

**Issue by Zwirek009** [filiprak/fileShare#20]
- Each host should have it's own folder with local files in it. 
- The folder should be stored in the local drive (in our example - not in shared folder with program code).
- The folder path should be specified by user on program init or be hardcoded.

**Comment by Zwirek009** [comment]
Critical risk of regression bugs --> to be done in separate branch (localfolder)

**Comment by filiprak** [comment]
In commit aa0ea477c2407cfadab5808e6a6f6d02d3d404ab added feature of creating directory "local.nick"
 under root directory of program executable. It was necessary to test tcp file transmitting.
