### ISSUE TITLE
Location of log files

### ISSUE THREAD

**Issue by Zwirek009** [filiprak/fileShare#25]
**Now:** log files are stored in directory from which app was runned
![image](https://cloud.githubusercontent.com/assets/10967805/26727682/f5c41d00-47a7-11e7-8bbd-0c6f403b591a.png)

**Should** be: log files stored in fileShare application location (eg in Log folder)
![image](https://cloud.githubusercontent.com/assets/10967805/26727917/b6c10d1a-47a8-11e7-94e2-e69219651fbb.png)

@filiprak should I move it or leave as it it now?

**Comment by filiprak** [comment]
In my opinion it's not so important issue, can be skipped.
