### ISSUE TITLE
Logged type of datagram change into name

### ISSUE THREAD

**Issue by Zwirek009** [filiprak/fileShare#29]
**Now:** type of datagram as code
**Should be: ** 
- type of datagram as a name (eg. "added_new_file")
OR
- description of numerical types of datagrams in log beginning

![image](https://cloud.githubusercontent.com/assets/10967805/26730385/0e648170-47b1-11e7-87e9-bf4a1da138f1.png)

@filiprak what do You think about it?

**Comment by filiprak** [comment]
Yes, it will help us to debug program definitely, but it may be overhead to do this
