### ISSUE TITLE
Unwanted extra newlines in log file after datagram received and send brodecast logs

### ISSUE THREAD

**Issue by Zwirek009** [filiprak/fileShare#30]
![image](https://cloud.githubusercontent.com/assets/10967805/26730521/87e2dc7c-47b1-11e7-8201-750a209073cf.png)

![image](https://cloud.githubusercontent.com/assets/10967805/26730921/c9ba02f0-47b2-11e7-8a2d-8b5825b6b803.png)

**Comment by filiprak** [comment]
it is minor issue, we can completely ignore that imo :)

**Comment by filiprak** [comment]
new line is appended in some text logs, including json serialized strings: { ... }\n
