### ISSUE TITLE
Wrong sequence of logs

### ISSUE THREAD

**Issue by Zwirek009** [filiprak/fileShare#31]
@filiprak Shouldn't it be first send brodecast and later dropped message from myself?

![image](https://cloud.githubusercontent.com/assets/10967805/26730965/df7276b8-47b2-11e7-92a7-0ce854f221e7.png)

**Comment by filiprak** [comment]
Yes, it should be, but notice that there are two different threads: 4460 and 4458, the time of log is the same, its issue of spdlog, we can ignore that
