### ISSUE TITLE
[CRITICAL] Waiting for response only from one node when add command !!!

### ISSUE THREAD

**Issue by Zwirek009** [filiprak/fileShare#32]
**Now:** When 4 nodes running, when file is added to one of them, the node waits only for response from **one** other node.

@filiprak Shouldn't it wait for **all three others**?

Here are all logs gained after the add:
![image](https://cloud.githubusercontent.com/assets/10967805/26731248/b81dd8c2-47b3-11e7-8ccd-c4f99f8621a0.png)

**Comment by filiprak** [comment]
It's okay, when first one node sends REQLIST to some alive node and then RESPLIST is broadcasted to all nodes, it was in our documentation.
