### ISSUE TITLE
Deleting files

### ISSUE THREAD

**Issue by Zwirek009** [filiprak/fileShare#33]
After file was deleted by owner, shouldnt it be deleted (not only wiped from the fle list list) in other nodes?

Also is the "Inconsistent..." when "ls" command on a host that has a file that was deleted by it's owner?

![image](https://cloud.githubusercontent.com/assets/10967805/26731927/06119be8-47b6-11e7-9a5b-af5af966c5ed.png)

**Comment by filiprak** [comment]
True, I will fix it ;)

**Comment by Zwirek009** [comment]
to be tested
